title: "[Paper Title]"
labels: ["New Paper"]
body:
  - type: textarea
    attributes:
      label: "Paper Details"
      description: |
        **Link**: 

        **Authors**: 

        **Abstract**: 

        **Notes**: 

        **Extra material**:
        