title: "[Propose a Paper for the Agents Reading Group]"
labels: ["New Paper"]
body:
  - type: textarea
    attributes:
      label: "Paper Title"

  - type: markdown
    attributes:
      value: |
        **Link**: 

        **Authors**: 

        **Abstract**: 

        **Notes**: 

        **Extra material**: