title: "[Paper Title] "
labels: ["New Paper"]
body:
  - type: textarea
    attributes:
      placeholder: |
        **Link**: 

        **Authors**: 

        **Abstract**: 

        **Notes**: 

        **Extra material**:
        